select * from customer
-->   what is the total revenue generated by male vs female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender
-->  Which customers used a discount but still spent more than the average purchaase amount?
select customer_id,purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer)

--> which are the top 5 products eith the highest average review rating?
select item_purchased,ROUND(avg(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--> compare the average purchase amounts between standard and express shipping
select shipping_type,
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')

group by shipping_type

--> Do subscribed custtomers spend more? compare average spend and total_revenue between subscribers and the non-subscribers

select subscription_status,
count(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

--> which 5 products have the highest percentage of purchases with discounts appiled?
select item_purchased,
ROUND(100 * SUM( CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;


--> segment customers innto new,returning, and loyal based ontheir total number of previous purchases and show the count of each segment.
with customer_type as(
select customer_id,previous_purchases,
CASE
	when previous_purchases = 1 THEN 'New'
	when previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	Else 'Loyal'
	END AS customer_segment
from customer
)
select customer_segment, count(*) as "Number of customers"
from customer_type
group by customer_segment
--> what are the top 3 most purchased products within each category?
with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id)  desc) as item_rank
from customer
group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank <= 3;

--> are customers who are repeaat buyers(more than 5 previous purchases) also likely to ubscribe?

select subscription_status,
count(customer_id) as repeat_buyers
from customer_shopping_behavior
where previous_purchases > 5
group by subscription_status


--> what is the revenue contribution of each age group?

select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;